# ==========================================
# Global DNS Daemon Settings
# ==========================================
port=53
listen-address=127.0.0.1,10.10.10.10
#bind-interfaces
bind-dynamic
# Never forward plain names (without a dot or domain part) up to public DNS
domain-needed
# Never forward reverse-lookup queries for private subnets up to public DNS
bogus-priv

# ==========================================
# Domain Configuration
# ==========================================
# Defines the local domain managed by this dnsmasq instance
domain=eptstech.arpa
# Tells dnsmasq to strictly resolve queries for this domain locally
local=/eptstech.arpa/

# ==========================================
# Forward Forwarding (A Records)
# Format: address=/hostname.domain/IP
# ==========================================
address=/ns1.eptstech.arpa/10.10.10.10
address=/anycast.eptstech.arpa/10.10.10.10

# ==========================================
# Reverse Lookup (PTR Records)
# Format: ptr-record=reversed-ip.in-addr.arpa,hostname
# ==========================================
# Reverse for Anycast IP 10.10.10.10
ptr-record=10.10.10.10.in-addr.arpa,anycast.eptstech.arpa

# ==========================================
# CNAME Records (Aliases)
# Format: cname=alias,target
# ==========================================
# Point www to the anycast A record
#cname=www.eptstech.arpa,anycast.eptstech.arpa

# Point dns to the anycast A record
cname=dns.eptstech.arpa,anycast.eptstech.arpa

# ==========================================
# IPv6 Forward Forwarding (AAAA Records)
# Same syntax as IPv4, dnsmasq auto-detects IPv6
# ==========================================
# address=/anycast.eptstech.arpa/2001:db8::10
# address=/bird-any-1.eptstech.arpa/2001:db8::2

# ==========================================
# IPv6 Reverse Lookup (PTR Records)
# Format: ptr-record=reversed-nibbles.ip6.arpa,hostname
# ==========================================
# Reverse for 2001:db8::10
# ptr-record=0.1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.b.d.0.1.0.0.2.ip6.arpa,anycast.eptstech.arpa