frr version 10.2.6_git
frr defaults traditional
hostname frr-ed2
no ipv6 forwarding
!
ip prefix-list CEOS-65002 seq 10 permit 172.16.1.0/24
ip prefix-list FROM-65004 seq 10 permit 172.18.1.0/24
!
ip route 192.0.2.1/32 blackhole
!
interface eth1
 ip address 10.0.3.5/30
 ip ospf area 0
 ip ospf cost 1
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 10.0.3.2/30
 ip ospf area 0
 ip ospf cost 1
 ip ospf network point-to-point
exit
!
interface eth3
 ip address 10.0.2.18/30
 ip ospf area 0
 ip ospf cost 1
 ip ospf network point-to-point
exit
!
interface eth4
 ip address 10.0.4.5/30
exit
!
interface eth5
 ip address 10.0.6.5/30
exit
!
interface lo
 ip address 10.0.1.4/32
 ip ospf area 0
exit
!
router bgp 65000
 bgp router-id 10.0.1.4
 no bgp ebgp-requires-policy
 no bgp default ipv4-unicast
 neighbor RR peer-group
 neighbor RR remote-as 65000
 neighbor RR update-source 10.0.1.4
 neighbor 10.0.1.1 peer-group RR
 neighbor 10.0.1.2 peer-group RR
 neighbor 10.0.4.6 remote-as 65002
 neighbor 10.0.6.6 remote-as 65004
 !
 address-family ipv4 unicast
  neighbor RR activate
  neighbor RR next-hop-self
  neighbor 10.0.4.6 activate
  neighbor 10.0.4.6 route-map CEOS-65002-IN in
  neighbor 10.0.6.6 activate
  neighbor 10.0.6.6 route-map FROM-65004-IN in
 exit-address-family
 !
 address-family ipv4 flowspec
  neighbor RR activate
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.1.4
exit
!
bgp community-list standard CEOS-65002-1 seq 5 permit 65002:120
bgp community-list standard CEOS-65002-2 seq 5 permit 65002:90
!
route-map CEOS-65002-IN permit 10
 match community CEOS-65002-1
 set local-preference 120
exit
!
route-map CEOS-65002-IN permit 20
 match community CEOS-65002-2
 set local-preference 90
exit
!
route-map CEOS-65002-IN permit 30
 match ip address prefix-list CEOS-65002
exit
!
route-map FROM-65004-IN permit 10
 match ip address prefix-list FROM-65004
exit
!
route-map TO-IBGP permit 10
exit
!
