log syslog all;
router id 10.0.5.2;

include "/etc/bird/flowspec.conf";

# Define Local Environment Constants
define SITE_COMM_PRIMARY = (65001, 120);   # High Priority
define SITE_COMM_BACKUP  = (65001, 80);    # Low Priority
define LOCAL_SITE_TAG    = (65001, 1001);  # I am Site A
define BLACKHOLE         = (65001, 666);  # Black-hole community

protocol device {}

# Pulls routes directly assigned to the Linux interface into BIRD
protocol direct {
    ipv4;           
    interface "any0";
}

protocol kernel {
    ipv4 {          
          import none;  
          export none;  
    };
}

# Unified policy name
filter export_to_pe {
    if net = 10.10.10.10/32 then {
        bgp_community.add(SITE_COMM_PRIMARY);
        #bgp_community.add(SITE_COMM_BACKUP);
        #bgp_community.add(BLACKHOLE);
        bgp_community.add(LOCAL_SITE_TAG);
        accept;
    }
    if net = 11.11.11.11/32 then {
        #bgp_community.add(SITE_COMM_PRIMARY);
        bgp_community.add(LOCAL_SITE_TAG);
        accept;
    }
    reject;
}

protocol bgp to_pe1 {
    local 10.0.5.2 as 65001;
    neighbor 10.0.5.1 as 65000;
    ipv4 { 
        import none; 
        export filter export_to_pe;
    };
    flow4 {
        table flowtab4;
        import none;
        #export none;
        export all;
    };
    hold time 30;
    graceful restart on;       # Enables the Graceful Restart extension
    
    # Optional Tuning Parameters:
    # graceful restart time 120;   # How many seconds the peer should keep traffic flowing while BIRD boots
    # graceful restart long lived on; # Enables LLGR (Long-Lived) for keeping routes even longer during massive outages
}