!
no aaa root
!
username admin privilege 15 role network-admin secret sha512 $6$dujp43OIZi5I8cyZ$8AlHQFx6mSlDk6qr0SuA8VFcC9eNj4JpVv9MBN7bL2m98qfuQsBmzgCgTMYBy/6465gOFiPLOYWhGOkIbJaIW.
!
management api http-commands
   no shutdown
!
no service interface inactive port-id allocation disabled
!
service routing protocols model multi-agent
!
hostname inet-ceos
!
spanning-tree mode mstp
!
system l1
   unsupported speed action error
   unsupported error-correction action error
!
management api gnmi
   transport grpc default
!
management api netconf
   transport ssh default
!
interface Ethernet1
   no switchport
   ip address 10.0.4.2/30
!
interface Ethernet2
   no switchport
   ip address 10.0.4.6/30
!
interface Ethernet3
   no switchport
   ip address 172.16.1.1/24
!
ip routing
!
ip as-path access-list in-65000 permit ^65000.* any
ip as-path access-list out-65000 permit ^$ any
ip prefix-list lan seq 1 permit 172.16.1.0/24
ip community-list wan1 permit 65002:120
ip community-list wan2 permit 65002:90
!
route-map from-65000 permit 1
   match as-path in-65000
   set as-path prepend last-as 2
!
route-map from-ebgp permit 1
   set local-preference 120
!
route-map to-ebgp permit 1
   match ip address prefix-list lan
   set community community-list wan1
!
route-map to-ebgp2 permit 1
   match ip address prefix-list lan
   set community community-list wan2
!
router bgp 65002
   router-id 172.16.1.1
   neighbor 10.0.4.1 remote-as 65000
   neighbor 10.0.4.1 route-map from-ebgp in
   neighbor 10.0.4.1 route-map to-ebgp out
   neighbor 10.0.4.1 send-community standard
   neighbor 10.0.4.5 remote-as 65000
   neighbor 10.0.4.5 route-map to-ebgp2 out
   neighbor 10.0.4.5 send-community standard
   !
   address-family ipv4
      neighbor 10.0.4.1 activate
      neighbor 10.0.4.5 activate
      network 172.16.1.0/24
!
end