frr defaults traditional
hostname inet-frr1
no ipv6 forwarding
!
ip prefix-list from-isp seq 5 permit any
ip prefix-list to-isp seq 5 permit 172.17.1.0/24
!
interface eth1
 ip address 10.0.6.2/30
exit
!
interface eth2
 ip address 172.17.1.1/24
exit
!
router bgp 65003
 bgp router-id 172.17.1.1
 no bgp default ipv4-unicast
 neighbor 10.0.6.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 172.17.1.0/24
  neighbor 10.0.6.1 activate
  neighbor 10.0.6.1 prefix-list from-isp in
  neighbor 10.0.6.1 route-map to-isp out
 exit-address-family
exit
!
bgp as-path access-list own seq 5 permit ^$
!
route-map to-isp permit 1
 match ip address prefix-list to-isp
exit
!
