flow4 table flowtab4;

# Static FlowSpec Rule
protocol static flow_mitigation {
    flow4 { table flowtab4; };

    # Rule 1: Drop DDOS UDP/53 traffic from Attacker to Target 10.10.10.10
    route flow4 {
        dst 10.10.10.10/32;   # Target DNS IP
        proto 17;             # UDP
        dport 53;             # DNS Port
        length 512..1500;
    } {
        # Set Traffic-Rate to 0 (DROP)
        bgp_ext_community.add((generic, 0x80060000, 0x00000000));
    };

    # Rule 2: Drop attacker IP (e.g., 172.16.1.5) targeting 10.10.10.10
    # route flow4 {
    #     src 172.18.1.2/32;    # Attacker 2
    #     dst 10.10.10.10/32;   # Target DNS IP
    #     proto 17;             # UDP
    #     dport 53;             # DNS Port
    # } {
    #     bgp_ext_community.add((generic, 0x80060000, 0x00000000));
    # };
    
    # Rule 3: Drop TCP syn-flood attack
    route flow4 {
        # Type 1 & Type 2: Destination and Source Subnets
        dst 10.10.10.10/32;     
        proto 6;                # Type 3: IP Protocol (TCP = 6)
        dport 8000;             # Type 5: Destination Port
        tcp flags 0x02/0x02;    # Type 9: TCP Flags (Matching SYN bit only: SYN=0x02, Mask=0x02)
        length 40..54;
    } {
        # Set Traffic-Rate to 0 (DROP)
        bgp_ext_community.add((generic, 0x80060000, 0x00000000));
    };
}