frr version 10.2.6_git
frr defaults traditional
hostname rtbh
no ipv6 forwarding
!
ip route 192.0.2.1/32 blackhole
!
interface eth1
 ip address 10.0.2.22/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface eth2
 ip address 10.0.2.26/30
 ip ospf area 0
 ip ospf network point-to-point
exit
!
interface lo
 ip address 10.0.1.7/32
 ip ospf area 0
exit
!
router bgp 65000
 bgp router-id 10.0.1.7
 no bgp default ipv4-unicast
 neighbor rr peer-group
 neighbor rr remote-as 65000
 neighbor rr update-source 10.0.1.7
 neighbor 10.0.1.1 peer-group rr
 neighbor 10.0.1.2 peer-group rr
 !
 address-family ipv4 unicast
  redistribute static route-map rtbh
  neighbor 10.0.1.1 activate
  neighbor 10.0.1.2 activate
 exit-address-family
exit
!
router ospf
 ospf router-id 10.0.1.7
exit
!
route-map rtbh permit 10
 match tag 666
 set community no-export
 set ip next-hop 192.0.2.1
 set local-preference 200
 set origin igp
exit
!
